In [ ]:
import numpy as np

In [ ]:
# prompt: a=np.array([1,2,3])

b=np.array([4,5,6])

In [ ]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b=np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [ ]:
a.ndim

1

In [ ]:
b.shape

(2, 2)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.itemsize

8

In [ ]:
a.nbytes

24

In [ ]:
b.nbytes

32

In [ ]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [ ]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
a.shape

(2, 7)

In [ ]:
a[1,5]

np.int64(13)

In [ ]:
a[1,-2]

np.int64(13)

In [ ]:
a[1]

array([ 8,  9, 10, 11, 12, 13, 14])

In [ ]:
a[:,2]

array([ 3, 10])

In [ ]:
a[0,1:-1:2]

array([2, 4, 6])

In [ ]:
a[:,2]=[1,2]

In [ ]:
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 13 14]]


In [ ]:
a[2,:]=[1,2,3,4,5,6,7]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [ ]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
np.random.random_sample(a.shape)

array([[0.58861692, 0.16462303, 0.68146308, 0.89841653, 0.14951645,
        0.38006009, 0.26893662],
       [0.64909609, 0.68678637, 0.86632876, 0.02181059, 0.83974681,
        0.13796902, 0.49483934]])

In [ ]:
np.random.randint(2,8, size=(3,3))

array([[5, 2, 7],
       [4, 4, 6],
       [5, 4, 7]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [ ]:
output=np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
z=np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
z[1,1]=9

In [ ]:
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
b=output.copy()
print(b)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
b+2

array([[ 3.,  3.,  3.,  3.,  3.],
       [ 3.,  2.,  2.,  2.,  3.],
       [ 3.,  2., 11.,  2.,  3.],
       [ 3.,  2.,  2.,  2.,  3.],
       [ 3.,  3.,  3.,  3.,  3.]])

In [ ]:
b/2

array([[0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0. , 0. , 0. , 0.5],
       [0.5, 0. , 4.5, 0. , 0.5],
       [0.5, 0. , 0. , 0. , 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5]])

In [ ]:
np.sin(b)

array([[0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098],
       [0.84147098, 0.        , 0.        , 0.        , 0.84147098],
       [0.84147098, 0.        , 0.41211849, 0.        , 0.84147098],
       [0.84147098, 0.        , 0.        , 0.        , 0.84147098],
       [0.84147098, 0.84147098, 0.84147098, 0.84147098, 0.84147098]])

In [ ]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [ ]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [ ]:
c=np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [ ]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats,axis=1)

array([1, 4])

In [ ]:
np.max(stats)

np.int64(6)

In [ ]:
np.sum(stats,axis=1)

array([ 6, 15])

In [ ]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
after=before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
h1=np.ones((2,4))
h2=np.zeros((2,2))
print(h1)
print(h2)
np.hstack((h1,h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

FileNotFoundError: 1,2,3,4,5,6 not found.

In [ ]:
output>3

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [ ]:
output[output>3]

array([9.])

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [ ]:
a[[1,2,8]]

array([2, 3, 9])